server:
  port: 8080
spring:
  datasource:
    name: dbtest
    url: jdbc:mysql://10.33.106.50:3306/dbtest?useUnicode=true&characterEncoding=UTF-8
    username: hdic_admin
    password: 654321
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: main.pojo